"""block_rows_side_nullable

Revision ID: 313f7c949a26
Revises: 91946d777a17
Create Date: 2026-04-27 11:48:46.369234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313f7c949a26'
down_revision: Union[str, Sequence[str], None] = '91946d777a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_rows', 'side',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_rows', 'side',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###
