"""create_block_rows_table

Revision ID: 91946d777a17
Revises: b8d51d5e0ee6
Create Date: 2026-04-27 11:42:06.232884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91946d777a17'
down_revision: Union[str, Sequence[str], None] = 'b8d51d5e0ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_rows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=1), nullable=False),
    sa.Column('variety_id', sa.Uuid(), nullable=False),
    sa.Column('clone_id', sa.Uuid(), nullable=False),
    sa.Column('rootstock_id', sa.Uuid(), nullable=True),
    sa.Column('planting_year', sa.Integer(), nullable=True),
    sa.Column('row_width_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('tree_spacing_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('tree_count', sa.Integer(), nullable=True),
    sa.Column('row_length_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['clone_id'], ['variety_clones.id'], ),
    sa.ForeignKeyConstraint(['rootstock_id'], ['rootstocks.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'row_number', 'side')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_rows')
    # ### end Alembic commands ###
