"""add_address_to_sites

Revision ID: e95cd5aed7a4
Revises: 05027b7cb8e1
Create Date: 2026-04-25 07:23:10.189997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95cd5aed7a4'
down_revision: Union[str, Sequence[str], None] = '05027b7cb8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'address')
    # ### end Alembic commands ###
